home/urls.py
from django.urls import path
from.import views
app_name ='home'

######################################################



from .views import  SiteRegisterOkView, SiteRegisterView, SiteLogoutView, IndexClass, LoginClass, ViewUser
urlpatterns = [
    #path('',views.index, name = 'home'),
#]




########################################################
########################################################


#urlpatterns = [
#    path('', IndexClass.as_view(), name='index'),

#    path('', ViewUser.as_view(),name='user_view'),
    path('', ViewUser.as_view(),name='home'),

    path('login/', LoginClass.as_view(), name='login'),
    path('user-view/', ViewUser.as_view(),name='user_view'),
    path('logout/',SiteLogoutView.as_view(),name='logout'),
    path('register/',SiteRegisterView.as_view(),name='register'),
    path('ok/',SiteRegisterOkView.as_view(),name='register_ok'),
]

mxh/urls.py
from django.contrib import admin
from django.urls import path, include
from home import views

urlpatterns = [
    path('admin/', admin.site.urls),
#   path('',views.index,name="trang chu"),

    path('',include('home.urls')),
    path('home/',include('home.urls')),
    
    path('watch/',include('watch.urls')),
    path('contact/',include('contact.urls')),
    path('loginsys/',include('loginsys.urls')),
]

#    path('userlogin/',include('userlogin.urls')),
#    path('userlogin/',include('home.urls')),

watch/urls.py
#from mxh.home.views import watch
from django.urls import path
from.import views 
app_name = 'watch'

from .views import watch

urlpatterns = [
#    path('', views.watch, name = 'watch'),
    path('', watch.as_view(),name='watch'),

    path('watchhistory/', views.watchhistory,name='watchhistory'),
]

home/models.py
from django.db import models

# Create your models here.

home/views.py
from django.conf.urls import url
from django.shortcuts import render
from django.http import HttpResponse
# Create your views here.
def index(request):
    return render(request,'home/index.html')
    #return HttpResponse("trang chu")


#####################################################################
#####################################################################

from pprint import pp
from typing import Reversible
from django.forms import widgets
from django.shortcuts import redirect, render, HttpResponse
from django.views import View
from django.contrib.auth import authenticate, login, decorators
from django.contrib.auth.views import LoginView, LogoutView
from django.views.generic import FormView
from django.contrib.auth.forms import UserCreationForm, UsernameField
from django import forms
from django.contrib.auth.models import User
from django.views.generic.base import TemplateView
from django.urls import reverse
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth import decorators
# Create your views here.

class IndexClass(View):
    def get(self, request):
        return HttpResponse('<h1>Xin chao</h1>')

class RegisterForm(UserCreationForm):
    email = forms.EmailField(required=True, widget=forms.EmailInput(attrs={'data-id': 1000}))
    class Meta:
        model = User
        fields = ('username', 'email')
        field_classes = {'username': UsernameField}
        widgets = {
        }

class SiteRegisterView(FormView):
    template_name = 'userlogin/register.html'
    form_class = RegisterForm

    def form_valid(self, form):
        data = form.cleaned_data
        new_user = User.objects.create_user(
            username=data['username'],
            password=data['password1'],
            email=data['email']
        )
        url = f"{reverse('home:register_ok')}?username={new_user.username}"
        return redirect(url)
        #from pprint import pprint; pprint(data)

class SiteRegisterOkView(TemplateView):
    template_name = 'userlogin/register_ok.html'
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['username'] = self.request.GET.get('usename')
        return context

class LoginClass(View):
    def get(self, request):
        return render(request,'userlogin/login.html')
    def post(self, request):
        tendangnhap = request.POST.get('tendangnhap')
        matkhau = request.POST.get('matkhau')
        my_user = authenticate(username=tendangnhap, password=matkhau) 
        if my_user is None:
        #   return HttpResponse('<h1>Dang nhap thai bai!, User Khong ton tai !!!!!!!!!!!!!!!!!!!!!!!!!</h1>')
            return render(request, 'userlogin/loginsai.html')        
        login(request, my_user)
        #return HttpResponse('<h1>DANG NHAP THANH CONG</h1>')
        return render(request, 'home/index.html')

class ViewUser(LoginRequiredMixin, View): # 
    login_url = '/login/'
    def get(delf, request):
    #    if not request.user.is_authenticated:
    #        return HttpResponse('<h1>Ban vui long dang nhap !!!!!!!!!!!!!!!!!!</h1>')
        #    return render(request, 'userlogin/login.html')
    #    else:
            return render(request, 'home/index.html')

class SiteLogoutView(LogoutView):
    #LoginRequiredMixin, Logout
#    def get(delf, request):
#    template_name = 
#        return render(request, login_url = '/logout.html')


    def get(delf, request):
        return render(request,'userlogin/logout.html')
    def post(self, request):
        tendangnhap = request.POST.get('tendangnhap')
        matkhau = request.POST.get('matkhau')
        my_user = authenticate(username=tendangnhap, password=matkhau) 
        if my_user is None:
            return render(request, 'userlogin/loginsai.html')        
        login(request, my_user)
        return render(request, 'home/index.html')
        

home/templates/home/base.html
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]>      <html class="no-js"> <!-<![endif]-->
<html>
    <head>
        {% load static %}
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <link rel="icon" href="{% static 'images/2logo.png' %}" type="image/x-icon">        
        <title>Xin chào thế giới</title>
        <meta name="description" content="">
<!--        <meta name="viewport" content="width=device-width, initial-scale=1"> -->
        <link rel="stylesheet" href="{% static 'home/style.css' %}">        
        <script src="https://kit.fontawesome.com/079cdfee91.js" crossorigin="anonymous"></script>
    </head>
    <body>

        <!--[if lt IE 7]>
            <p class="browsehappy">You are using an <strong>outdated</strong> browser. Please <a href="#">upgrade your browser</a> to improve your experience.</p>
        <![endif]-->
        <nav>
            <div class="nav-left">
                    <a href="{% url 'home:home'%}"><img src="{% static 'images/logo1png.png' %}" class="logo"></a>     
                    <ul>
                        <li><a href="{% url 'home:home'%}"><img src="{% static 'images/home.png' %}"></a></li>
                        <li><a href="{% url 'watch:watch' %}"><img src="{% static 'images/video.png' %}"></a></li>
                        <li><a href="#"><img src="{% static 'images/video-short1.png' %}"></a></li>
                        <li><a href="#"><img src="{% static 'images/marketplace.png' %}"></a></li>
                    </ul>  
            </div>
            <div class="nav-right">
                <div class="search-box">
                    <img src="{% static 'images/search.png' %}">
                    <input type="text" placeholder="Search">
                </div>
                <div class="icon-notification">
                    <a href="#"><img src="{% static 'images/dollar.png' %}"></a>
                </div>
                <div class="icon-notification">
                    <a href="#"><img src="{% static 'images/email.png' %}"></a>
                </div>
                <div class="icon-notification">
                    <a href="#"><img src="{% static 'images/bell.png' %}"></a>
                </div>
                <div class="nav-user-icon " onclick="settingsMenuToggle()">
                    <img src="{% static 'images/profile-pic.jpg' %}">
                </div>
            </div>

            <!-- Start settings-menu -------------------------------- -->
            <div class="settings-menu">
                
                <div id="dark-btn" >               
                    <span></span>
                </div>
                
                <div class="settings-menu-inner">
                    <div class="user-profile">
                        <img src="{% static 'images/profile-pic.jpg' %}">
                        <div>
                            <p>{{ user.username}}</p>
                            <a href="#">See your profile</a>
                        </div>
                    </div>
                    <hr>
                    <div class="user-profile">
                        <img src="{% static 'images/feedback.png' %}">
                        <div>
                            <p>Give Feedback</p>
                            <a href="#">Help us to improve the new design</a>
                        </div>
                    </div>
                    <hr>
                    <div class="settings-links">
                        <img src="{% static 'images/settings.png' %}" class="settings-icon">
                        <a href="#"> Settings & Privacy <img src="{%static 'images/arrow.png' %}" width="10px"></a>
                    </div>
                    <div class="settings-links">
                        <img src="{% static 'images/help.png' %}" class="settings-icon">
                        <a href="#"> Help & Support <img src="{%static 'images/arrow.png' %}" width="10px"></a>
                    </div>
                    <div class="settings-links">
                        <img src="{% static 'images/display.png' %}" class="settings-icon">
                        <a href="#"> Display & Accessibility <img src="{%static 'images/arrow.png' %}" width="10px"></a>
                    </div>
                    <div class="settings-links">
                        <img src="{% static 'images/logout.png' %}" class="settings-icon">
                        <a href="{% url 'home:logout' %}"> Logout <img src="{%static 'images/arrow.png' %}" width="10px"></a>
                    </div>

                </div>                     
            </div>
            <!-- End settings-menu -------------------------------- -->
        </nav>

        <div class="container">
            {% block content %}

            {% endblock %}
        </div>

        <script src="{% static 'home/script.js' %}"></script>

        
    </body>
</html>