home/urls.py
from django.urls import path
from.import views
app_name ='home'

######################################################



from .views import  SiteRegisterOkView, SiteRegisterView, SiteLogoutView, IndexClass, LoginClass, ViewUser
urlpatterns = [
    #path('',views.index, name = 'home'),
#]




########################################################
########################################################


#urlpatterns = [
#    path('', IndexClass.as_view(), name='index'),

#    path('', ViewUser.as_view(),name='user_view'),
    path('', ViewUser.as_view(),name='home'),

    path('login/', LoginClass.as_view(), name='login'),
    path('user-view/', ViewUser.as_view(),name='user_view'),
    path('logout/',SiteLogoutView.as_view(),name='logout'),
    path('register/',SiteRegisterView.as_view(),name='register'),
    path('ok/',SiteRegisterOkView.as_view(),name='register_ok'),
]

mxh/urls.py
from django.contrib import admin
from django.urls import path, include
from home import views

urlpatterns = [
    path('admin/', admin.site.urls),
#   path('',views.index,name="trang chu"),

    path('',include('home.urls')),
    path('home/',include('home.urls')),
    
    path('watch/',include('watch.urls')),
    path('contact/',include('contact.urls')),
    path('loginsys/',include('loginsys.urls')),
]

#    path('userlogin/',include('userlogin.urls')),
#    path('userlogin/',include('home.urls')),

userlogin/urls.py
from django.urls import path
from .views import  SiteRegisterOkView, SiteRegisterView,  IndexClass, LoginClass, ViewUser #SiteLogoutView,



urlpatterns = [
    path('', IndexClass.as_view(), name='index'),
#    path('login/', LoginClass.as_view(), name='login'),
    path('user-view/', ViewUser.as_view(),name='user_view'),
 #   path('logout/',SiteLogoutView.as_view(),name='logout'),
    path('register',SiteRegisterView.as_view(),name='register'),
    path('register/ok',SiteRegisterOkView.as_view(),name='register_ok'),
]

home/models.py
from django.db import models

# Create your models here.

userlogin/models.py
from django.db import models

# Create your models here.

home/views.py
from django.conf.urls import url
from django.shortcuts import render
from django.http import HttpResponse
# Create your views here.
def index(request):
    return render(request,'home/index.html')
    #return HttpResponse("trang chu")


#####################################################################
#####################################################################

from pprint import pp
from typing import Reversible
from django.forms import widgets
from django.shortcuts import redirect, render, HttpResponse
from django.views import View
from django.contrib.auth import authenticate, login, decorators
from django.contrib.auth.views import LoginView, LogoutView
from django.views.generic import FormView
from django.contrib.auth.forms import UserCreationForm, UsernameField
from django import forms
from django.contrib.auth.models import User
from django.views.generic.base import TemplateView
from django.urls import reverse
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth import decorators
# Create your views here.

class IndexClass(View):
    def get(self, request):
        return HttpResponse('<h1>Xin chao</h1>')

class RegisterForm(UserCreationForm):
    email = forms.EmailField(required=True, widget=forms.EmailInput(attrs={'data-id': 1000}))
    class Meta:
        model = User
        fields = ('username', 'email')
        field_classes = {'username': UsernameField}
        widgets = {
        }

class SiteRegisterView(FormView):
    template_name = 'userlogin/register.html'
    form_class = RegisterForm

    def form_valid(self, form):
        data = form.cleaned_data
        new_user = User.objects.create_user(
            username=data['username'],
            password=data['password1'],
            email=data['email']
        )
        url = f"{reverse('home:register_ok')}?username={new_user.username}"
        return redirect(url)
        #from pprint import pprint; pprint(data)

class SiteRegisterOkView(TemplateView):
    template_name = 'userlogin/register_ok.html'
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['username'] = self.request.GET.get('usename')
        return context

class LoginClass(View):
    def get(self, request):
        return render(request,'userlogin/login.html')
    def post(self, request):
        tendangnhap = request.POST.get('tendangnhap')
        matkhau = request.POST.get('matkhau')
        my_user = authenticate(username=tendangnhap, password=matkhau) 
        if my_user is None:
        #   return HttpResponse('<h1>Dang nhap thai bai!, User Khong ton tai !!!!!!!!!!!!!!!!!!!!!!!!!</h1>')
            return render(request, 'userlogin/loginsai.html')        
        login(request, my_user)
        #return HttpResponse('<h1>DANG NHAP THANH CONG</h1>')
        return render(request, 'home/index.html')

class ViewUser(LoginRequiredMixin, View): # 
    login_url = '/login/'
    def get(delf, request):
    #    if not request.user.is_authenticated:
    #        return HttpResponse('<h1>Ban vui long dang nhap !!!!!!!!!!!!!!!!!!</h1>')
        #    return render(request, 'userlogin/login.html')
    #    else:
            return render(request, 'home/index.html')

class SiteLogoutView(LogoutView):
    #LoginRequiredMixin, Logout
#    def get(delf, request):
#    template_name = 
#        return render(request, login_url = '/logout.html')


    def get(delf, request):
        return render(request,'userlogin/logout.html')
    def post(self, request):
        tendangnhap = request.POST.get('tendangnhap')
        matkhau = request.POST.get('matkhau')
        my_user = authenticate(username=tendangnhap, password=matkhau) 
        if my_user is None:
            return render(request, 'userlogin/loginsai.html')        
        login(request, my_user)
        return render(request, 'home/index.html')
        

userlogin/views.py
from pprint import pp
from typing import Reversible
from django.forms import widgets
from django.shortcuts import redirect, render, HttpResponse

from django.views import View
from django.contrib.auth import authenticate, login, decorators

from django.contrib.auth.views import LoginView, LogoutView
from django.views.generic import FormView
from django.contrib.auth.forms import UserCreationForm, UsernameField
from django import forms
from django.contrib.auth.models import User
from django.views.generic.base import TemplateView
from django.urls import reverse
# Create your views here.

class IndexClass(View):
    def get(self, request):
        return HttpResponse('<h1>Xin chao</h1>')




class RegisterForm(UserCreationForm):
    email = forms.EmailField(required=True, widget=forms.EmailInput(attrs={'data-id': 1000}))

    class Meta:
        model = User
        fields = ('username', 'email')
        field_classes = {'username': UsernameField}
        widgets = {
        }

class SiteRegisterView(FormView):
    template_name = 'userlogin/register.html'
    form_class = RegisterForm

    def form_valid(self, form):
        data = form.cleaned_data
        new_user = User.objects.create_user(
            username=data['username'],
            password=data['password1'],
            email=data['email']
        )
        url = f"{reverse('register_ok')}?username={new_user.username}"
        return redirect(url)
        #from pprint import pprint; pprint(data)

class SiteRegisterOkView(TemplateView):
    template_name = 'userlogin/register_ok.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['username'] = self.request.GET.get('usename')
        return context


class LoginClass(View):
    def get(self, request):
        return render(request,'userlogin/login.html')

    def post(self, request):
        tendangnhap = request.POST.get('tendangnhap')
        matkhau = request.POST.get('matkhau')
        my_user = authenticate(username=tendangnhap, password=matkhau) 
        if my_user is None:
           return HttpResponse('<h1>Dang nhap thai bai!, User Khong ton tai !!!!!!!!!!!!!!!!!!!!!!!!!</h1>')
        
        login(request, my_user)
        return HttpResponse('<h1>DANG NHAP THANH CONG</h1>')

class ViewUser(View):
    def get(delf, request):
        if not request.user.is_authenticated:
            return HttpResponse('<h1>Ban vui long dang nhap !!!!!!!!!!!!!!!!!!</h1>')
        #    return render(request, 'userlogin/login.html')
        else:
            return render(request, 'userlogin/thanhcong.html')



#class SiteLogoutView(LogoutView):
#    template_name = 'userlogin/logout.html'

home/templates/userlogin/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <link rel="stylesheet" href="{% static 'home/style.css' %}">        
    <title>MXH - Đăng nhập hoặc đăng ký</title>
</head>
<body class="bodylogin">
    <div class="logologin">
        <img src="{% static 'images/logo1png.png' %}" >
    </div>
    <div class="Login">
        <form action="" method="post" >
            {% csrf_token %}
            <input type="text" name="tendangnhap" placeholder="Tên Đăng Nhập" class="input_login" required="True">
            <br>
            <input type="password" name="matkhau" placeholder="Mật khẩu" class="input_login" required="True">
            <br>
            <input type="submit" value="Đăng Nhập" class="nut_login">           
        </form>
            <hr/>
            <a href="{% url 'home:register' %}"><button class="nut_register">Tạo Tài Khoản Mới</button></a>
    </div>
</body>
</html>

home/templates/userlogin/loginsai.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <link rel="stylesheet" href="{% static 'home/style.css' %}">        
    <title>MXH - Đăng nhập hoặc đăng ký</title>
</head>
<body class="bodylogin">
    <div class="logologin">
        <img src="{% static 'images/logo1png.png' %}" >
    </div>
    <div class="Login">
        <form action="" method="post" >
            {% csrf_token %}
            <br>
            <div style='color:red;' class="doclogin">
                Tên tài khoản hoặc mật khẩu không đúng !
                <br> Vui lòng nhập lại:
            </div>
            <input type="text" name="tendangnhap" placeholder="Tên Đăng Nhập" class="input_login" required="True">
            <br>
            <input type="password" name="matkhau" placeholder="Mật khẩu" class="input_login" required="True">
            <br>
            <input type="submit" value="Đăng Nhập" class="nut_login">           
        </form>
            <hr/>
            <a href="{% url 'home:register' %}"><button class="nut_register">Tạo Tài Khoản Mới</button></a>
    </div>
</body>
</html>

home/templates/userlogin/logout.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <link rel="stylesheet" href="{% static 'home/style.css' %}">        
    <title>MXH - Đăng nhập hoặc đăng ký</title>
</head>
<body class="bodylogin">
    <div class="logologin">
        <img src="{% static 'images/logo1png.png' %}" >
    </div>
    <div class="Login">
        <form action="" method="post" >
            {% csrf_token %}
            <br>
            <div style='color:red;' class="doclogin">
                Bạn đã đăng xuất khỏi tài khoản !
                <br> Đăng nhập lại tại đây:
            </div>
            <input type="text" name="tendangnhap" placeholder="Tên Đăng Nhập" class="input_login" required="True">
            <br>
            <input type="password" name="matkhau" placeholder="Mật khẩu" class="input_login" required="True">
            <br>
            <input type="submit" value="Đăng Nhập" class="nut_login">           
        </form>
            <hr/>
            <a href="{% url 'home:register' %}"><button class="nut_register">Tạo Tài Khoản Mới</button></a>
    </div>
</body>
</html>

home/templates/userlogin/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %} -->
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'home/style.css' %}">        
    <title>Đăng ký tài khoản mới</title>
</head>
<body>
    <div>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit"> DANG KY </button>
        </form>
    </div>
</body>
</html>

home/templates/userlogin/register_ok.html
{% extends 'home/base.html' %}
    {% load static %}
    {% block content %}
        <div class="register_ok" style='color:blue;'>
            <h1>Chào mừng {{ username }} đến với mạng xã hội </h1>
            <h1>Chúc bạn tham gia vui vẻ</h1>           
            <a href="{% url 'home:login' %}" ><button class="nut_login_home"> Đăng nhập tham gia ngay </button></a>
        </div>
{% endblock %}
        