loginsys/urls.py
from django.contrib import admin
from django.urls import path
from django.views.generic.base import View
from.import views


app_name ='loginsys'

urlpatterns = [
    path('',views.loginsys, name ='loginsys'),
    path('Registration',views.Userreg, name="Reg"),
    path('login', views.loginpage,name="Loginpage"),
    path('logout', views.logout,name="Logout"),
    
    path('testlogin/', views.loginpage, name="testlogin" )
]

mxh/urls.py
from django.contrib import admin
from django.urls import path, include
from home import views

urlpatterns = [
    path('admin/', admin.site.urls),
#   path('',views.index,name="trang chu"),

    path('',include('home.urls')),
    path('home/',include('home.urls')),
    
    path('watch/',include('watch.urls')),
    path('contact/',include('contact.urls')),
    path('loginsys/',include('loginsys.urls')),
]

#    path('userlogin/',include('userlogin.urls')),
#    path('userlogin/',include('home.urls')),

loginsys/models.py
from django.db import models
from datetime import datetime
from django.contrib.auth.models import User

# Create your models here.

class Newuser(models.Model):
    Username=models.CharField(max_length=150)
    Email=models.CharField(max_length=150)
    Pwd=models.CharField(max_length=150)
    Age=models.IntegerField()
    Gender=models.CharField(max_length=1)
    Martialstatus=models.CharField(max_length=150)

loginsys/views.py
from django.shortcuts import render
from django.http import HttpResponse, request
from loginsys.models import Newuser
from django.contrib import messages

# Create your views here.
def loginsys(request):
    return render(request,'loginsys/loginsys.html')

def Userreg(request):
    if request.method=='POST':
        Username=request.POST['Username']
        Email=request.POST['Email']
        Pwd=request.POST['Pwd']
        Age=request.POST['Age']
        Gender=request.POST['Gender']
        Martialstatus=request.POST['Martialstatus']
        Newuser(Username=Username,Email=Email,Pwd=Pwd,Age=Age,Gender=Gender,Martialstatus=Martialstatus).save() 
        messages.success(request,'The New User'+ request.POST['Username'] + "Is Saved Successfully...!")
        return render(request,'loginsys/Registration.html')
    else:
        return render(request, 'loginsys/Registration.html')    



def loginpage(request):
    if request.method=="POST":
        try:
            Userdetails=Newuser.objects.get(Email=request.POST['Email'], Pwd=request.POST['Pwd'])
            print("Username=", Userdetails)
            request.session['Email']=Userdetails.Email
        #    if not request.session['Email']:
        #            return render(request,'loginsys/loginsys.html')
        #    else: 
        #            return render(request,'loginsys/testlogin.html')
            return render(request,'loginsys/loginsys.html')
        #    return render(request,'home/index.html')
        except Newuser.DoesNotExist as e:
            messages.success(request,'Username | Password Invalid...!')    
    return render(request,'loginsys/login.html')
    #return render(request,'home/index.html')



def logout(request):
    try:
        del request.session['Email']
    except:
        return render(request,'loginsys/loginsys.html')
    return render(request,'loginsys/loginsys.html')
 


#def get(request):
#    if not request.session['Email']:
#        return render(request,'loginsys/login.html')
#    else: 
#        return render(request,'loginsys/testlogin.html')

loginsys/templates/loginsys/Registration.html
<h1>Nguoi dung dang ky tai khoan moi</h1>
<hr/>
<form method="POST">
    {% csrf_token %} 
    <table border="1">
        <tr>
            <td>User Name</td>
            <td><input type="text" placeholder="Enter Username" name="Username" required></td>
        </tr>
        <tr>
            <td>Email</td>
            <td><input type="Email" placeholder="Enter Email" name="Email" required></td>
        </tr>
        <tr>
            <td>Password</td>
            <td><input type="password" placeholder="Enter Password" name="Pwd" required></td>
        </tr>
        <tr>
            <td>Age</td>
            <td><input type="text" placeholder="Enter Age" name="Age" required></td>
        </tr>
        <tr>
            <td>Gender</td>
            <td>
                <input type="radio" value="M" name="Gender"> Male |
                <input type="radio" value="F" name="Gender"> Female
            </td>
        </tr>
        <tr>
            <td>Marital Status</td>
            <td>
                <select name="Martialstatus">
                    <option value="Married">Married</option>
                    <option value="UnMarried">UnMarried</option>
                    <option value="Divorced">Divorced</option>
                </select>
            </td>
        </tr>
        <tr>
            <td></td>
            <td>
                <button type="submit">Registration</button>
            </td>
        </tr>
    </table>
    {% if messages %}
    {% for msg in messages %}
    <b>{{msg}}</b>
    {% endfor %}
    {% endif %}
    </hr>
    <em>If You Already A Member <a href="{% url 'loginsys:Loginpage' %}">Sign In</a> </em>
</form>

loginsys/templates/loginsys/login.html
<h1>Trang Đăng Nhập</h1>
<hr/>
<form action="" method="POST">
    {% csrf_token %}
    <table border="1">
        <tr>
            <td>
                User Name
            </td>
            <td><input type="text" placeholder="Enter User Name... " name="Email" required></td>
        </tr>
        <tr>
            <td>
                Password
            </td>
            <td><input type="password" placeholder="Enter Password..." name="Pwd" required></td>
        </tr>        
        <tr>
            <td></td>
            <td>
                <button type="submit">Login</button>
            </td>
        </tr>
    </table>
    {% if messages %}
    {% for msg in messages %}
    <b>{{msg}}</b>
    {% endfor %}
    {% endif %}
</form>

loginsys/templates/loginsys/loginsys.html
{% if request.session.Email %}
    {{ request.session.Email }} &nbsp;&nbsp; <a href="{% url 'loginsys:Logout' %}">Logout</a>
    
{% else %}
    <h1>Trang index Login Logout Register</h1>
    <hr/>
    <b>
        <a href="{% url 'loginsys:Reg' %}">Registration</a> &nbsp;&nbsp; | &nbsp;&nbsp;
        <a href="{% url 'loginsys:Loginpage' %}">Login</a>
    </b>
{% endif %}